theme: jekyll-theme-cayman
title: Cleansy Photos
description: Remove old photos quickly
author: Roman Kartsev
plugins:
  - jekyll-seo-tag
google_analytics: UA-167527274-1
webmaster_verifications:
  yandex: 80e5f6811abbb85d